name: Tests

on:
  push:
    branches:
      - main

jobs:
  rustup_test_aarch64:
    name: rustup_test_aarch64
    runs-on: "ubuntu-22.04-arm"

    steps:
      - uses: actions/checkout@v4

      - name: Run
        run: |
          env
          cat ~/.rustup/settings.toml
          sha512sum ~/.cargo/bin/rustup

          rustup self update
          rustup -V

          cargo clippy
