name: Tests

on:
  push:
    branches:
      - main

jobs:
  rustup_test:
    name: rustup_test
    runs-on: "ubuntu-22.04-arm"

    steps:
      - uses: actions/checkout@v4

      - name: Run
        run: |
          env
          cat ~/.rustup/settings.toml
          sha512sum ~/.cargo/bin/rustup

          rustup -V

          rustup --verbose toolchain install nightly-2025-04-25
